FROM centos:centos6.6
MAINTAINER Wattana Inthaphong <wattaint@gmail.com>
# enable centos plus repo and install epel repo
RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm \
 && rpm -iUvh http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm \
 && yum update -y \
 && yum install -y make patch libyaml-devel libffi-devel glibc-headers autoconf gcc-c++ glibc-devel patch readline-devel zlib-devel openssl-devel bzip2 automake libtool bison \
 && yum install -y postgresql94 postgresql94-devel postgresql94-libs postgresql94-server \
 && yum install -y wget monit mlocate vim which tar \
 && yum clean all
#RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/6/x86_64/e/epel-release-7-5.noarch.rpm
# install necessary utilities
#RUN rpm -iUvh http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm

#RUN yum update -y; yum clean all

#RUN yum install -y make patch libyaml-devel libffi-devel glibc-headers autoconf gcc-c++ glibc-devel patch readline-devel zlib-devel openssl-devel bzip2 automake libtool bison; yum clean all
#RUN yum install -y postgresql94 postgresql94-devel postgresql94-libs postgresql94-server; yum clean all
#RUN yum install -y wget monit mlocate vim which tar; yum clean all
